/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCommandLinkButton>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLineEdit *CT1;
    QLineEdit *CT2;
    QLineEdit *CT3;
    QLineEdit *CT4;
    QLineEdit *CT5;
    QLineEdit *CT6;
    QLineEdit *te2;
    QLineEdit *te6;
    QLineEdit *te1;
    QLineEdit *te4;
    QLineEdit *te3;
    QLineEdit *te5;
    QLineEdit *tmp2;
    QLineEdit *tmp6;
    QLineEdit *tmp1;
    QLineEdit *tmp4;
    QLineEdit *tmp3;
    QLineEdit *tmp5;
    QLineEdit *a5;
    QLineEdit *a2;
    QLineEdit *a6;
    QLineEdit *a4;
    QLineEdit *a1;
    QLineEdit *a3;
    QLineEdit *tc5;
    QLineEdit *tc2;
    QLineEdit *tc6;
    QLineEdit *tc4;
    QLineEdit *tc1;
    QLineEdit *tc3;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QCommandLinkButton *SALIR;
    QPushButton *pushButton;
    QFrame *line;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLineEdit *CT2_2;
    QLineEdit *CT1_2;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLineEdit *CT2_3;
    QLineEdit *CT1_3;
    QLineEdit *CT2_4;
    QLineEdit *CT1_4;
    QLineEdit *CT2_5;
    QLineEdit *CT1_5;
    QLineEdit *CT2_6;
    QLineEdit *CT1_6;
    QLineEdit *CT2_7;
    QLineEdit *CT1_7;
    QLineEdit *CT2_8;
    QLineEdit *CT1_8;
    QLineEdit *CT2_9;
    QLineEdit *CT1_9;
    QLabel *label_36;
    QLabel *label_37;
    QLineEdit *te2_2;
    QLineEdit *tmp2_2;
    QLineEdit *CT2_10;
    QLineEdit *CT1_10;
    QLineEdit *te1_2;
    QLineEdit *tmp1_2;
    QLabel *label_38;
    QLineEdit *CT2_11;
    QLineEdit *CT2_12;
    QLineEdit *CT2_13;
    QLineEdit *CT2_14;
    QLineEdit *CT2_15;
    QLineEdit *CT2_16;
    QLineEdit *CT1_11;
    QLineEdit *CT1_12;
    QLineEdit *CT2_17;
    QLineEdit *CT2_18;
    QLineEdit *CT1_13;
    QLineEdit *CT1_14;
    QLineEdit *CT1_15;
    QLineEdit *CT1_16;
    QLineEdit *CT1_17;
    QLineEdit *CT1_18;
    QLineEdit *CT2_19;
    QLineEdit *CT2_20;
    QLineEdit *CT2_21;
    QLineEdit *CT2_22;
    QLineEdit *CT2_23;
    QLineEdit *CT2_24;
    QLineEdit *CT2_25;
    QLineEdit *CT2_26;
    QLineEdit *CT1_19;
    QLineEdit *CT2_27;
    QLineEdit *CT2_28;
    QLabel *label_39;
    QLineEdit *tmp2_3;
    QLineEdit *te1_3;
    QLineEdit *CT2_29;
    QLineEdit *CT1_20;
    QLabel *label_40;
    QLineEdit *CT2_30;
    QLineEdit *CT2_31;
    QLineEdit *CT1_21;
    QLineEdit *CT2_32;
    QLineEdit *tmp1_3;
    QLineEdit *CT2_33;
    QLineEdit *CT1_22;
    QLineEdit *CT1_23;
    QLineEdit *CT1_24;
    QLineEdit *CT2_34;
    QLineEdit *CT2_35;
    QLineEdit *CT2_36;
    QLabel *label_41;
    QLineEdit *CT2_37;
    QLineEdit *CT2_38;
    QLineEdit *CT2_39;
    QLineEdit *CT1_25;
    QLineEdit *CT2_40;
    QLineEdit *CT1_26;
    QLineEdit *CT2_41;
    QLineEdit *te2_3;
    QLabel *label_42;
    QLabel *label_43;
    QLineEdit *CT1_27;
    QLabel *label_44;
    QLineEdit *CT2_42;
    QLabel *label_45;
    QLineEdit *CT2_43;
    QLabel *label_46;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1443, 945);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(380, 30, 111, 31));
        QFont font;
        font.setPointSize(15);
        label->setFont(font);
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(500, 30, 111, 31));
        label_2->setFont(font);
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(620, 30, 111, 31));
        label_3->setFont(font);
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(740, 30, 111, 31));
        label_4->setFont(font);
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(860, 30, 111, 31));
        label_5->setFont(font);
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(980, 30, 111, 31));
        label_6->setFont(font);
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(1100, 30, 111, 31));
        label_7->setFont(font);
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(1220, 30, 111, 31));
        label_8->setFont(font);
        CT1 = new QLineEdit(centralwidget);
        CT1->setObjectName(QString::fromUtf8("CT1"));
        CT1->setGeometry(QRect(740, 80, 81, 31));
        CT1->setFont(font);
        CT2 = new QLineEdit(centralwidget);
        CT2->setObjectName(QString::fromUtf8("CT2"));
        CT2->setGeometry(QRect(740, 120, 81, 31));
        CT2->setFont(font);
        CT3 = new QLineEdit(centralwidget);
        CT3->setObjectName(QString::fromUtf8("CT3"));
        CT3->setGeometry(QRect(740, 160, 81, 31));
        CT3->setFont(font);
        CT4 = new QLineEdit(centralwidget);
        CT4->setObjectName(QString::fromUtf8("CT4"));
        CT4->setGeometry(QRect(740, 200, 81, 31));
        CT4->setFont(font);
        CT5 = new QLineEdit(centralwidget);
        CT5->setObjectName(QString::fromUtf8("CT5"));
        CT5->setGeometry(QRect(740, 240, 81, 31));
        CT5->setFont(font);
        CT6 = new QLineEdit(centralwidget);
        CT6->setObjectName(QString::fromUtf8("CT6"));
        CT6->setGeometry(QRect(740, 280, 81, 31));
        CT6->setFont(font);
        te2 = new QLineEdit(centralwidget);
        te2->setObjectName(QString::fromUtf8("te2"));
        te2->setGeometry(QRect(850, 120, 81, 31));
        te2->setFont(font);
        te6 = new QLineEdit(centralwidget);
        te6->setObjectName(QString::fromUtf8("te6"));
        te6->setGeometry(QRect(850, 280, 81, 31));
        te6->setFont(font);
        te1 = new QLineEdit(centralwidget);
        te1->setObjectName(QString::fromUtf8("te1"));
        te1->setGeometry(QRect(850, 80, 81, 31));
        te1->setFont(font);
        te4 = new QLineEdit(centralwidget);
        te4->setObjectName(QString::fromUtf8("te4"));
        te4->setGeometry(QRect(850, 200, 81, 31));
        te4->setFont(font);
        te3 = new QLineEdit(centralwidget);
        te3->setObjectName(QString::fromUtf8("te3"));
        te3->setGeometry(QRect(850, 160, 81, 31));
        te3->setFont(font);
        te5 = new QLineEdit(centralwidget);
        te5->setObjectName(QString::fromUtf8("te5"));
        te5->setGeometry(QRect(850, 240, 81, 31));
        te5->setFont(font);
        tmp2 = new QLineEdit(centralwidget);
        tmp2->setObjectName(QString::fromUtf8("tmp2"));
        tmp2->setGeometry(QRect(970, 120, 81, 31));
        tmp2->setFont(font);
        tmp6 = new QLineEdit(centralwidget);
        tmp6->setObjectName(QString::fromUtf8("tmp6"));
        tmp6->setGeometry(QRect(970, 280, 81, 31));
        tmp6->setFont(font);
        tmp1 = new QLineEdit(centralwidget);
        tmp1->setObjectName(QString::fromUtf8("tmp1"));
        tmp1->setGeometry(QRect(970, 80, 81, 31));
        tmp1->setFont(font);
        tmp4 = new QLineEdit(centralwidget);
        tmp4->setObjectName(QString::fromUtf8("tmp4"));
        tmp4->setGeometry(QRect(970, 200, 81, 31));
        tmp4->setFont(font);
        tmp3 = new QLineEdit(centralwidget);
        tmp3->setObjectName(QString::fromUtf8("tmp3"));
        tmp3->setGeometry(QRect(970, 160, 81, 31));
        tmp3->setFont(font);
        tmp5 = new QLineEdit(centralwidget);
        tmp5->setObjectName(QString::fromUtf8("tmp5"));
        tmp5->setGeometry(QRect(970, 240, 81, 31));
        tmp5->setFont(font);
        a5 = new QLineEdit(centralwidget);
        a5->setObjectName(QString::fromUtf8("a5"));
        a5->setGeometry(QRect(1080, 240, 81, 31));
        a5->setFont(font);
        a2 = new QLineEdit(centralwidget);
        a2->setObjectName(QString::fromUtf8("a2"));
        a2->setGeometry(QRect(1080, 120, 81, 31));
        a2->setFont(font);
        a6 = new QLineEdit(centralwidget);
        a6->setObjectName(QString::fromUtf8("a6"));
        a6->setGeometry(QRect(1080, 280, 81, 31));
        a6->setFont(font);
        a4 = new QLineEdit(centralwidget);
        a4->setObjectName(QString::fromUtf8("a4"));
        a4->setGeometry(QRect(1080, 200, 81, 31));
        a4->setFont(font);
        a1 = new QLineEdit(centralwidget);
        a1->setObjectName(QString::fromUtf8("a1"));
        a1->setGeometry(QRect(1080, 80, 81, 31));
        a1->setFont(font);
        a3 = new QLineEdit(centralwidget);
        a3->setObjectName(QString::fromUtf8("a3"));
        a3->setGeometry(QRect(1080, 160, 81, 31));
        a3->setFont(font);
        tc5 = new QLineEdit(centralwidget);
        tc5->setObjectName(QString::fromUtf8("tc5"));
        tc5->setGeometry(QRect(1220, 240, 81, 31));
        tc5->setFont(font);
        tc2 = new QLineEdit(centralwidget);
        tc2->setObjectName(QString::fromUtf8("tc2"));
        tc2->setGeometry(QRect(1220, 120, 81, 31));
        tc2->setFont(font);
        tc6 = new QLineEdit(centralwidget);
        tc6->setObjectName(QString::fromUtf8("tc6"));
        tc6->setGeometry(QRect(1220, 280, 81, 31));
        tc6->setFont(font);
        tc4 = new QLineEdit(centralwidget);
        tc4->setObjectName(QString::fromUtf8("tc4"));
        tc4->setGeometry(QRect(1220, 200, 81, 31));
        tc4->setFont(font);
        tc1 = new QLineEdit(centralwidget);
        tc1->setObjectName(QString::fromUtf8("tc1"));
        tc1->setGeometry(QRect(1220, 80, 81, 31));
        tc1->setFont(font);
        tc3 = new QLineEdit(centralwidget);
        tc3->setObjectName(QString::fromUtf8("tc3"));
        tc3->setGeometry(QRect(1220, 160, 81, 31));
        tc3->setFont(font);
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(100, 20, 71, 51));
        QFont font1;
        font1.setPointSize(30);
        label_9->setFont(font1);
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(640, 80, 51, 31));
        label_10->setFont(font);
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(640, 120, 51, 31));
        label_11->setFont(font);
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(640, 160, 51, 31));
        label_12->setFont(font);
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(640, 200, 51, 31));
        label_13->setFont(font);
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(640, 240, 51, 31));
        label_14->setFont(font);
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(640, 280, 51, 31));
        label_15->setFont(font);
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(500, 120, 51, 31));
        label_16->setFont(font);
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(500, 240, 51, 31));
        label_17->setFont(font);
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(390, 120, 51, 31));
        label_18->setFont(font);
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(390, 240, 51, 31));
        label_19->setFont(font);
        SALIR = new QCommandLinkButton(centralwidget);
        SALIR->setObjectName(QString::fromUtf8("SALIR"));
        SALIR->setGeometry(QRect(100, 200, 172, 41));
        pushButton = new QPushButton(centralwidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(80, 130, 131, 51));
        pushButton->setFont(font);
        line = new QFrame(centralwidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(30, 340, 1251, 20));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(490, 380, 111, 31));
        label_20->setFont(font);
        label_21 = new QLabel(centralwidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(730, 380, 111, 31));
        label_21->setFont(font);
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(970, 380, 111, 31));
        label_22->setFont(font);
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(40, 380, 111, 31));
        label_23->setFont(font);
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(610, 380, 111, 31));
        label_24->setFont(font);
        label_25 = new QLabel(centralwidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(1210, 380, 111, 31));
        label_25->setFont(font);
        label_26 = new QLabel(centralwidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(1090, 380, 111, 31));
        label_26->setFont(font);
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(850, 380, 111, 31));
        label_27->setFont(font);
        label_28 = new QLabel(centralwidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(1320, 380, 111, 31));
        label_28->setFont(font);
        label_29 = new QLabel(centralwidget);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(40, 430, 231, 31));
        label_29->setFont(font);
        label_30 = new QLabel(centralwidget);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(40, 470, 231, 31));
        label_30->setFont(font);
        CT2_2 = new QLineEdit(centralwidget);
        CT2_2->setObjectName(QString::fromUtf8("CT2_2"));
        CT2_2->setGeometry(QRect(460, 470, 111, 31));
        CT2_2->setFont(font);
        CT1_2 = new QLineEdit(centralwidget);
        CT1_2->setObjectName(QString::fromUtf8("CT1_2"));
        CT1_2->setGeometry(QRect(460, 430, 111, 31));
        CT1_2->setFont(font);
        label_31 = new QLabel(centralwidget);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(40, 580, 111, 31));
        label_31->setFont(font);
        label_32 = new QLabel(centralwidget);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(90, 520, 111, 31));
        label_32->setFont(font);
        label_33 = new QLabel(centralwidget);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(110, 560, 51, 31));
        label_33->setFont(font);
        label_34 = new QLabel(centralwidget);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(110, 610, 51, 31));
        label_34->setFont(font);
        label_35 = new QLabel(centralwidget);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(180, 520, 111, 31));
        label_35->setFont(font);
        CT2_3 = new QLineEdit(centralwidget);
        CT2_3->setObjectName(QString::fromUtf8("CT2_3"));
        CT2_3->setGeometry(QRect(580, 470, 111, 31));
        CT2_3->setFont(font);
        CT1_3 = new QLineEdit(centralwidget);
        CT1_3->setObjectName(QString::fromUtf8("CT1_3"));
        CT1_3->setGeometry(QRect(580, 430, 111, 31));
        CT1_3->setFont(font);
        CT2_4 = new QLineEdit(centralwidget);
        CT2_4->setObjectName(QString::fromUtf8("CT2_4"));
        CT2_4->setGeometry(QRect(700, 470, 111, 31));
        CT2_4->setFont(font);
        CT1_4 = new QLineEdit(centralwidget);
        CT1_4->setObjectName(QString::fromUtf8("CT1_4"));
        CT1_4->setGeometry(QRect(700, 430, 111, 31));
        CT1_4->setFont(font);
        CT2_5 = new QLineEdit(centralwidget);
        CT2_5->setObjectName(QString::fromUtf8("CT2_5"));
        CT2_5->setGeometry(QRect(820, 470, 111, 31));
        CT2_5->setFont(font);
        CT1_5 = new QLineEdit(centralwidget);
        CT1_5->setObjectName(QString::fromUtf8("CT1_5"));
        CT1_5->setGeometry(QRect(820, 430, 111, 31));
        CT1_5->setFont(font);
        CT2_6 = new QLineEdit(centralwidget);
        CT2_6->setObjectName(QString::fromUtf8("CT2_6"));
        CT2_6->setGeometry(QRect(940, 470, 111, 31));
        CT2_6->setFont(font);
        CT1_6 = new QLineEdit(centralwidget);
        CT1_6->setObjectName(QString::fromUtf8("CT1_6"));
        CT1_6->setGeometry(QRect(940, 430, 111, 31));
        CT1_6->setFont(font);
        CT2_7 = new QLineEdit(centralwidget);
        CT2_7->setObjectName(QString::fromUtf8("CT2_7"));
        CT2_7->setGeometry(QRect(1060, 470, 111, 31));
        CT2_7->setFont(font);
        CT1_7 = new QLineEdit(centralwidget);
        CT1_7->setObjectName(QString::fromUtf8("CT1_7"));
        CT1_7->setGeometry(QRect(1060, 430, 111, 31));
        CT1_7->setFont(font);
        CT2_8 = new QLineEdit(centralwidget);
        CT2_8->setObjectName(QString::fromUtf8("CT2_8"));
        CT2_8->setGeometry(QRect(1180, 470, 111, 31));
        CT2_8->setFont(font);
        CT1_8 = new QLineEdit(centralwidget);
        CT1_8->setObjectName(QString::fromUtf8("CT1_8"));
        CT1_8->setGeometry(QRect(1180, 430, 111, 31));
        CT1_8->setFont(font);
        CT2_9 = new QLineEdit(centralwidget);
        CT2_9->setObjectName(QString::fromUtf8("CT2_9"));
        CT2_9->setGeometry(QRect(1300, 470, 111, 31));
        CT2_9->setFont(font);
        CT1_9 = new QLineEdit(centralwidget);
        CT1_9->setObjectName(QString::fromUtf8("CT1_9"));
        CT1_9->setGeometry(QRect(1300, 430, 111, 31));
        CT1_9->setFont(font);
        label_36 = new QLabel(centralwidget);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(270, 520, 111, 31));
        label_36->setFont(font);
        label_37 = new QLabel(centralwidget);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(370, 520, 111, 31));
        label_37->setFont(font);
        te2_2 = new QLineEdit(centralwidget);
        te2_2->setObjectName(QString::fromUtf8("te2_2"));
        te2_2->setGeometry(QRect(250, 610, 81, 31));
        te2_2->setFont(font);
        tmp2_2 = new QLineEdit(centralwidget);
        tmp2_2->setObjectName(QString::fromUtf8("tmp2_2"));
        tmp2_2->setGeometry(QRect(340, 610, 81, 31));
        tmp2_2->setFont(font);
        CT2_10 = new QLineEdit(centralwidget);
        CT2_10->setObjectName(QString::fromUtf8("CT2_10"));
        CT2_10->setGeometry(QRect(160, 610, 81, 31));
        CT2_10->setFont(font);
        CT1_10 = new QLineEdit(centralwidget);
        CT1_10->setObjectName(QString::fromUtf8("CT1_10"));
        CT1_10->setGeometry(QRect(160, 560, 81, 31));
        CT1_10->setFont(font);
        te1_2 = new QLineEdit(centralwidget);
        te1_2->setObjectName(QString::fromUtf8("te1_2"));
        te1_2->setGeometry(QRect(250, 560, 81, 31));
        te1_2->setFont(font);
        tmp1_2 = new QLineEdit(centralwidget);
        tmp1_2->setObjectName(QString::fromUtf8("tmp1_2"));
        tmp1_2->setGeometry(QRect(340, 560, 81, 31));
        tmp1_2->setFont(font);
        label_38 = new QLabel(centralwidget);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(360, 660, 111, 31));
        label_38->setFont(font);
        CT2_11 = new QLineEdit(centralwidget);
        CT2_11->setObjectName(QString::fromUtf8("CT2_11"));
        CT2_11->setGeometry(QRect(580, 610, 111, 31));
        CT2_11->setFont(font);
        CT2_12 = new QLineEdit(centralwidget);
        CT2_12->setObjectName(QString::fromUtf8("CT2_12"));
        CT2_12->setGeometry(QRect(820, 610, 111, 31));
        CT2_12->setFont(font);
        CT2_13 = new QLineEdit(centralwidget);
        CT2_13->setObjectName(QString::fromUtf8("CT2_13"));
        CT2_13->setGeometry(QRect(940, 610, 111, 31));
        CT2_13->setFont(font);
        CT2_14 = new QLineEdit(centralwidget);
        CT2_14->setObjectName(QString::fromUtf8("CT2_14"));
        CT2_14->setGeometry(QRect(1060, 610, 111, 31));
        CT2_14->setFont(font);
        CT2_15 = new QLineEdit(centralwidget);
        CT2_15->setObjectName(QString::fromUtf8("CT2_15"));
        CT2_15->setGeometry(QRect(1300, 610, 111, 31));
        CT2_15->setFont(font);
        CT2_16 = new QLineEdit(centralwidget);
        CT2_16->setObjectName(QString::fromUtf8("CT2_16"));
        CT2_16->setGeometry(QRect(700, 610, 111, 31));
        CT2_16->setFont(font);
        CT1_11 = new QLineEdit(centralwidget);
        CT1_11->setObjectName(QString::fromUtf8("CT1_11"));
        CT1_11->setGeometry(QRect(700, 560, 111, 31));
        CT1_11->setFont(font);
        CT1_12 = new QLineEdit(centralwidget);
        CT1_12->setObjectName(QString::fromUtf8("CT1_12"));
        CT1_12->setGeometry(QRect(820, 560, 111, 31));
        CT1_12->setFont(font);
        CT2_17 = new QLineEdit(centralwidget);
        CT2_17->setObjectName(QString::fromUtf8("CT2_17"));
        CT2_17->setGeometry(QRect(460, 610, 111, 31));
        CT2_17->setFont(font);
        CT2_18 = new QLineEdit(centralwidget);
        CT2_18->setObjectName(QString::fromUtf8("CT2_18"));
        CT2_18->setGeometry(QRect(1180, 610, 111, 31));
        CT2_18->setFont(font);
        CT1_13 = new QLineEdit(centralwidget);
        CT1_13->setObjectName(QString::fromUtf8("CT1_13"));
        CT1_13->setGeometry(QRect(1300, 560, 111, 31));
        CT1_13->setFont(font);
        CT1_14 = new QLineEdit(centralwidget);
        CT1_14->setObjectName(QString::fromUtf8("CT1_14"));
        CT1_14->setGeometry(QRect(1060, 560, 111, 31));
        CT1_14->setFont(font);
        CT1_15 = new QLineEdit(centralwidget);
        CT1_15->setObjectName(QString::fromUtf8("CT1_15"));
        CT1_15->setGeometry(QRect(460, 560, 111, 31));
        CT1_15->setFont(font);
        CT1_16 = new QLineEdit(centralwidget);
        CT1_16->setObjectName(QString::fromUtf8("CT1_16"));
        CT1_16->setGeometry(QRect(580, 560, 111, 31));
        CT1_16->setFont(font);
        CT1_17 = new QLineEdit(centralwidget);
        CT1_17->setObjectName(QString::fromUtf8("CT1_17"));
        CT1_17->setGeometry(QRect(1180, 560, 111, 31));
        CT1_17->setFont(font);
        CT1_18 = new QLineEdit(centralwidget);
        CT1_18->setObjectName(QString::fromUtf8("CT1_18"));
        CT1_18->setGeometry(QRect(940, 560, 111, 31));
        CT1_18->setFont(font);
        CT2_19 = new QLineEdit(centralwidget);
        CT2_19->setObjectName(QString::fromUtf8("CT2_19"));
        CT2_19->setGeometry(QRect(1300, 660, 111, 31));
        CT2_19->setFont(font);
        CT2_20 = new QLineEdit(centralwidget);
        CT2_20->setObjectName(QString::fromUtf8("CT2_20"));
        CT2_20->setGeometry(QRect(1060, 660, 111, 31));
        CT2_20->setFont(font);
        CT2_21 = new QLineEdit(centralwidget);
        CT2_21->setObjectName(QString::fromUtf8("CT2_21"));
        CT2_21->setGeometry(QRect(700, 660, 111, 31));
        CT2_21->setFont(font);
        CT2_22 = new QLineEdit(centralwidget);
        CT2_22->setObjectName(QString::fromUtf8("CT2_22"));
        CT2_22->setGeometry(QRect(580, 660, 111, 31));
        CT2_22->setFont(font);
        CT2_23 = new QLineEdit(centralwidget);
        CT2_23->setObjectName(QString::fromUtf8("CT2_23"));
        CT2_23->setGeometry(QRect(940, 660, 111, 31));
        CT2_23->setFont(font);
        CT2_24 = new QLineEdit(centralwidget);
        CT2_24->setObjectName(QString::fromUtf8("CT2_24"));
        CT2_24->setGeometry(QRect(1180, 660, 111, 31));
        CT2_24->setFont(font);
        CT2_25 = new QLineEdit(centralwidget);
        CT2_25->setObjectName(QString::fromUtf8("CT2_25"));
        CT2_25->setGeometry(QRect(460, 660, 111, 31));
        CT2_25->setFont(font);
        CT2_26 = new QLineEdit(centralwidget);
        CT2_26->setObjectName(QString::fromUtf8("CT2_26"));
        CT2_26->setGeometry(QRect(820, 660, 111, 31));
        CT2_26->setFont(font);
        CT1_19 = new QLineEdit(centralwidget);
        CT1_19->setObjectName(QString::fromUtf8("CT1_19"));
        CT1_19->setGeometry(QRect(160, 750, 81, 31));
        CT1_19->setFont(font);
        CT2_27 = new QLineEdit(centralwidget);
        CT2_27->setObjectName(QString::fromUtf8("CT2_27"));
        CT2_27->setGeometry(QRect(1180, 850, 111, 31));
        CT2_27->setFont(font);
        CT2_28 = new QLineEdit(centralwidget);
        CT2_28->setObjectName(QString::fromUtf8("CT2_28"));
        CT2_28->setGeometry(QRect(1180, 800, 111, 31));
        CT2_28->setFont(font);
        label_39 = new QLabel(centralwidget);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(370, 710, 111, 31));
        label_39->setFont(font);
        tmp2_3 = new QLineEdit(centralwidget);
        tmp2_3->setObjectName(QString::fromUtf8("tmp2_3"));
        tmp2_3->setGeometry(QRect(340, 800, 81, 31));
        tmp2_3->setFont(font);
        te1_3 = new QLineEdit(centralwidget);
        te1_3->setObjectName(QString::fromUtf8("te1_3"));
        te1_3->setGeometry(QRect(250, 750, 81, 31));
        te1_3->setFont(font);
        CT2_29 = new QLineEdit(centralwidget);
        CT2_29->setObjectName(QString::fromUtf8("CT2_29"));
        CT2_29->setGeometry(QRect(1300, 800, 111, 31));
        CT2_29->setFont(font);
        CT1_20 = new QLineEdit(centralwidget);
        CT1_20->setObjectName(QString::fromUtf8("CT1_20"));
        CT1_20->setGeometry(QRect(940, 750, 111, 31));
        CT1_20->setFont(font);
        label_40 = new QLabel(centralwidget);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(270, 710, 111, 31));
        label_40->setFont(font);
        CT2_30 = new QLineEdit(centralwidget);
        CT2_30->setObjectName(QString::fromUtf8("CT2_30"));
        CT2_30->setGeometry(QRect(460, 850, 111, 31));
        CT2_30->setFont(font);
        CT2_31 = new QLineEdit(centralwidget);
        CT2_31->setObjectName(QString::fromUtf8("CT2_31"));
        CT2_31->setGeometry(QRect(1060, 850, 111, 31));
        CT2_31->setFont(font);
        CT1_21 = new QLineEdit(centralwidget);
        CT1_21->setObjectName(QString::fromUtf8("CT1_21"));
        CT1_21->setGeometry(QRect(580, 750, 111, 31));
        CT1_21->setFont(font);
        CT2_32 = new QLineEdit(centralwidget);
        CT2_32->setObjectName(QString::fromUtf8("CT2_32"));
        CT2_32->setGeometry(QRect(1300, 850, 111, 31));
        CT2_32->setFont(font);
        tmp1_3 = new QLineEdit(centralwidget);
        tmp1_3->setObjectName(QString::fromUtf8("tmp1_3"));
        tmp1_3->setGeometry(QRect(340, 750, 81, 31));
        tmp1_3->setFont(font);
        CT2_33 = new QLineEdit(centralwidget);
        CT2_33->setObjectName(QString::fromUtf8("CT2_33"));
        CT2_33->setGeometry(QRect(160, 800, 81, 31));
        CT2_33->setFont(font);
        CT1_22 = new QLineEdit(centralwidget);
        CT1_22->setObjectName(QString::fromUtf8("CT1_22"));
        CT1_22->setGeometry(QRect(820, 750, 111, 31));
        CT1_22->setFont(font);
        CT1_23 = new QLineEdit(centralwidget);
        CT1_23->setObjectName(QString::fromUtf8("CT1_23"));
        CT1_23->setGeometry(QRect(460, 750, 111, 31));
        CT1_23->setFont(font);
        CT1_24 = new QLineEdit(centralwidget);
        CT1_24->setObjectName(QString::fromUtf8("CT1_24"));
        CT1_24->setGeometry(QRect(1300, 750, 111, 31));
        CT1_24->setFont(font);
        CT2_34 = new QLineEdit(centralwidget);
        CT2_34->setObjectName(QString::fromUtf8("CT2_34"));
        CT2_34->setGeometry(QRect(700, 850, 111, 31));
        CT2_34->setFont(font);
        CT2_35 = new QLineEdit(centralwidget);
        CT2_35->setObjectName(QString::fromUtf8("CT2_35"));
        CT2_35->setGeometry(QRect(940, 800, 111, 31));
        CT2_35->setFont(font);
        CT2_36 = new QLineEdit(centralwidget);
        CT2_36->setObjectName(QString::fromUtf8("CT2_36"));
        CT2_36->setGeometry(QRect(700, 800, 111, 31));
        CT2_36->setFont(font);
        label_41 = new QLabel(centralwidget);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(360, 850, 111, 31));
        label_41->setFont(font);
        CT2_37 = new QLineEdit(centralwidget);
        CT2_37->setObjectName(QString::fromUtf8("CT2_37"));
        CT2_37->setGeometry(QRect(820, 850, 111, 31));
        CT2_37->setFont(font);
        CT2_38 = new QLineEdit(centralwidget);
        CT2_38->setObjectName(QString::fromUtf8("CT2_38"));
        CT2_38->setGeometry(QRect(580, 800, 111, 31));
        CT2_38->setFont(font);
        CT2_39 = new QLineEdit(centralwidget);
        CT2_39->setObjectName(QString::fromUtf8("CT2_39"));
        CT2_39->setGeometry(QRect(940, 850, 111, 31));
        CT2_39->setFont(font);
        CT1_25 = new QLineEdit(centralwidget);
        CT1_25->setObjectName(QString::fromUtf8("CT1_25"));
        CT1_25->setGeometry(QRect(700, 750, 111, 31));
        CT1_25->setFont(font);
        CT2_40 = new QLineEdit(centralwidget);
        CT2_40->setObjectName(QString::fromUtf8("CT2_40"));
        CT2_40->setGeometry(QRect(460, 800, 111, 31));
        CT2_40->setFont(font);
        CT1_26 = new QLineEdit(centralwidget);
        CT1_26->setObjectName(QString::fromUtf8("CT1_26"));
        CT1_26->setGeometry(QRect(1180, 750, 111, 31));
        CT1_26->setFont(font);
        CT2_41 = new QLineEdit(centralwidget);
        CT2_41->setObjectName(QString::fromUtf8("CT2_41"));
        CT2_41->setGeometry(QRect(1060, 800, 111, 31));
        CT2_41->setFont(font);
        te2_3 = new QLineEdit(centralwidget);
        te2_3->setObjectName(QString::fromUtf8("te2_3"));
        te2_3->setGeometry(QRect(250, 800, 81, 31));
        te2_3->setFont(font);
        label_42 = new QLabel(centralwidget);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(180, 710, 111, 31));
        label_42->setFont(font);
        label_43 = new QLabel(centralwidget);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(110, 800, 51, 31));
        label_43->setFont(font);
        CT1_27 = new QLineEdit(centralwidget);
        CT1_27->setObjectName(QString::fromUtf8("CT1_27"));
        CT1_27->setGeometry(QRect(1060, 750, 111, 31));
        CT1_27->setFont(font);
        label_44 = new QLabel(centralwidget);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(40, 770, 111, 31));
        label_44->setFont(font);
        CT2_42 = new QLineEdit(centralwidget);
        CT2_42->setObjectName(QString::fromUtf8("CT2_42"));
        CT2_42->setGeometry(QRect(820, 800, 111, 31));
        CT2_42->setFont(font);
        label_45 = new QLabel(centralwidget);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(110, 750, 51, 31));
        label_45->setFont(font);
        CT2_43 = new QLineEdit(centralwidget);
        CT2_43->setObjectName(QString::fromUtf8("CT2_43"));
        CT2_43->setGeometry(QRect(580, 850, 111, 31));
        CT2_43->setFont(font);
        label_46 = new QLabel(centralwidget);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(90, 710, 111, 31));
        label_46->setFont(font);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1443, 21));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        label->setText(QApplication::translate("MainWindow", "Item", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Ruta", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Operaci\303\263n", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "CTk", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "tei", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "tmp", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "ai", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "tcijk (h.e.)", nullptr));
        CT1->setText(QString());
        CT2->setText(QString());
        CT3->setText(QString());
        CT4->setText(QString());
        CT5->setText(QString());
        CT6->setText(QString());
        te2->setText(QString());
        te6->setText(QString());
        te1->setText(QString());
        te4->setText(QString());
        te3->setText(QString());
        te5->setText(QString());
        tmp2->setText(QString());
        tmp6->setText(QString());
        tmp1->setText(QString());
        tmp4->setText(QString());
        tmp3->setText(QString());
        tmp5->setText(QString());
        a5->setText(QString());
        a2->setText(QString());
        a6->setText(QString());
        a4->setText(QString());
        a1->setText(QString());
        a3->setText(QString());
        tc5->setText(QString());
        tc2->setText(QString());
        tc6->setText(QString());
        tc4->setText(QString());
        tc1->setText(QString());
        tc3->setText(QString());
        label_9->setText(QApplication::translate("MainWindow", "CRP", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "O1", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "O2", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "O3", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "O4", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "O5", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "O6", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "1", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "2", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "A", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "B", nullptr));
        SALIR->setText(QApplication::translate("MainWindow", "SALIR", nullptr));
        pushButton->setText(QApplication::translate("MainWindow", "EJECUTAR", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "1", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "3", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "5", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "Periodos", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "2", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "7", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "6", nullptr));
        label_27->setText(QApplication::translate("MainWindow", "4", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "8", nullptr));
        label_29->setText(QApplication::translate("MainWindow", "Pedidos planificados de A", nullptr));
        label_30->setText(QApplication::translate("MainWindow", "Pedidos planificados de B", nullptr));
        CT2_2->setText(QString());
        CT1_2->setText(QString());
        label_31->setText(QApplication::translate("MainWindow", "CT1", nullptr));
        label_32->setText(QApplication::translate("MainWindow", "Item", nullptr));
        label_33->setText(QApplication::translate("MainWindow", "A", nullptr));
        label_34->setText(QApplication::translate("MainWindow", "B", nullptr));
        label_35->setText(QApplication::translate("MainWindow", "TCjk", nullptr));
        CT2_3->setText(QString());
        CT1_3->setText(QString());
        CT2_4->setText(QString());
        CT1_4->setText(QString());
        CT2_5->setText(QString());
        CT1_5->setText(QString());
        CT2_6->setText(QString());
        CT1_6->setText(QString());
        CT2_7->setText(QString());
        CT1_7->setText(QString());
        CT2_8->setText(QString());
        CT1_8->setText(QString());
        CT2_9->setText(QString());
        CT1_9->setText(QString());
        label_36->setText(QApplication::translate("MainWindow", "Qe", nullptr));
        label_37->setText(QApplication::translate("MainWindow", "Aj", nullptr));
        te2_2->setText(QString());
        tmp2_2->setText(QString());
        CT2_10->setText(QString());
        CT1_10->setText(QString());
        te1_2->setText(QString());
        tmp1_2->setText(QString());
        label_38->setText(QApplication::translate("MainWindow", "Total", nullptr));
        CT2_11->setText(QString());
        CT2_12->setText(QString());
        CT2_13->setText(QString());
        CT2_14->setText(QString());
        CT2_15->setText(QString());
        CT2_16->setText(QString());
        CT1_11->setText(QString());
        CT1_12->setText(QString());
        CT2_17->setText(QString());
        CT2_18->setText(QString());
        CT1_13->setText(QString());
        CT1_14->setText(QString());
        CT1_15->setText(QString());
        CT1_16->setText(QString());
        CT1_17->setText(QString());
        CT1_18->setText(QString());
        CT2_19->setText(QString());
        CT2_20->setText(QString());
        CT2_21->setText(QString());
        CT2_22->setText(QString());
        CT2_23->setText(QString());
        CT2_24->setText(QString());
        CT2_25->setText(QString());
        CT2_26->setText(QString());
        CT1_19->setText(QString());
        CT2_27->setText(QString());
        CT2_28->setText(QString());
        label_39->setText(QApplication::translate("MainWindow", "Aj", nullptr));
        tmp2_3->setText(QString());
        te1_3->setText(QString());
        CT2_29->setText(QString());
        CT1_20->setText(QString());
        label_40->setText(QApplication::translate("MainWindow", "Qe", nullptr));
        CT2_30->setText(QString());
        CT2_31->setText(QString());
        CT1_21->setText(QString());
        CT2_32->setText(QString());
        tmp1_3->setText(QString());
        CT2_33->setText(QString());
        CT1_22->setText(QString());
        CT1_23->setText(QString());
        CT1_24->setText(QString());
        CT2_34->setText(QString());
        CT2_35->setText(QString());
        CT2_36->setText(QString());
        label_41->setText(QApplication::translate("MainWindow", "Total", nullptr));
        CT2_37->setText(QString());
        CT2_38->setText(QString());
        CT2_39->setText(QString());
        CT1_25->setText(QString());
        CT2_40->setText(QString());
        CT1_26->setText(QString());
        CT2_41->setText(QString());
        te2_3->setText(QString());
        label_42->setText(QApplication::translate("MainWindow", "TCjk", nullptr));
        label_43->setText(QApplication::translate("MainWindow", "B", nullptr));
        CT1_27->setText(QString());
        label_44->setText(QApplication::translate("MainWindow", "CT2", nullptr));
        CT2_42->setText(QString());
        label_45->setText(QApplication::translate("MainWindow", "A", nullptr));
        CT2_43->setText(QString());
        label_46->setText(QApplication::translate("MainWindow", "Item", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
