/********************************************************************************
** Form generated from reading UI file 'crp.ui'
**
** Created by: Qt User Interface Compiler version 5.12.12
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CRP_H
#define UI_CRP_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCommandLinkButton>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CRP
{
public:
    QWidget *centralwidget;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLineEdit *CT1;
    QLineEdit *CT2;
    QLineEdit *CT3;
    QLineEdit *CT4;
    QLineEdit *CT5;
    QLineEdit *CT6;
    QLineEdit *te2;
    QLineEdit *te6;
    QLineEdit *te1;
    QLineEdit *te4;
    QLineEdit *te3;
    QLineEdit *te5;
    QLineEdit *tmp2;
    QLineEdit *tmp6;
    QLineEdit *tmp1;
    QLineEdit *tmp4;
    QLineEdit *tmp3;
    QLineEdit *tmp5;
    QLineEdit *a5;
    QLineEdit *a2;
    QLineEdit *a6;
    QLineEdit *a4;
    QLineEdit *a1;
    QLineEdit *a3;
    QLineEdit *tc5;
    QLineEdit *tc2;
    QLineEdit *tc6;
    QLineEdit *tc4;
    QLineEdit *tc1;
    QLineEdit *tc3;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QCommandLinkButton *SALIR;
    QPushButton *Ejecutar;
    QFrame *line;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLineEdit *PPB_1;
    QLineEdit *PPA_1;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLineEdit *PPB_3;
    QLineEdit *PPA_3;
    QLineEdit *PPB_4;
    QLineEdit *PPA_4;
    QLineEdit *PPB_5;
    QLineEdit *PPA_5;
    QLineEdit *PPB_6;
    QLineEdit *PPA_6;
    QLineEdit *PPB_7;
    QLineEdit *PPA_7;
    QLineEdit *PPB_8;
    QLineEdit *PPA_8;
    QLineEdit *PPB_2;
    QLineEdit *PPA_2;
    QLabel *label_36;
    QLabel *label_37;
    QLineEdit *QB1;
    QLineEdit *AJB1;
    QLineEdit *TCB1;
    QLineEdit *TC1A;
    QLineEdit *QA1;
    QLineEdit *AJA1;
    QLabel *label_38;
    QLineEdit *CT1B_2;
    QLineEdit *CT1B_4;
    QLineEdit *CT1B_5;
    QLineEdit *CT1B_6;
    QLineEdit *CT1B_8;
    QLineEdit *CT1B_3;
    QLineEdit *CT1A_3;
    QLineEdit *CT1A_4;
    QLineEdit *CT1B_1;
    QLineEdit *CT1B_7;
    QLineEdit *CT1A_8;
    QLineEdit *CT1A_6;
    QLineEdit *CT1A_1;
    QLineEdit *CT1A_2;
    QLineEdit *CT1A_7;
    QLineEdit *CT1A_5;
    QLineEdit *T1_8;
    QLineEdit *T1_6;
    QLineEdit *T1_3;
    QLineEdit *T1_2;
    QLineEdit *T1_5;
    QLineEdit *T1_7;
    QLineEdit *T1_1;
    QLineEdit *T1_4;
    QLineEdit *TC2A;
    QLineEdit *T2_7;
    QLineEdit *CT2B_7;
    QLabel *label_39;
    QLineEdit *AJB2;
    QLineEdit *QA2;
    QLineEdit *CT2B_8;
    QLineEdit *CT2A_5;
    QLabel *label_40;
    QLineEdit *T2_1;
    QLineEdit *T2_6;
    QLineEdit *CT2A_2;
    QLineEdit *T2_8;
    QLineEdit *AJA2;
    QLineEdit *TC2B;
    QLineEdit *CT2A_4;
    QLineEdit *CT2A_1;
    QLineEdit *CT2A_8;
    QLineEdit *T2_3;
    QLineEdit *CT2B_5;
    QLineEdit *CT2B_3;
    QLabel *label_41;
    QLineEdit *T2_4;
    QLineEdit *CT2B_2;
    QLineEdit *T2_5;
    QLineEdit *CT2A_3;
    QLineEdit *CT2B_1;
    QLineEdit *CT2A_7;
    QLineEdit *CT2B_6;
    QLineEdit *QB2;
    QLabel *label_42;
    QLabel *label_43;
    QLineEdit *CT2A_6;
    QLabel *label_44;
    QLineEdit *CT2B_4;
    QLabel *label_45;
    QLineEdit *T2_2;
    QLabel *label_46;
    QLabel *label_47;
    QLineEdit *TsA;
    QLineEdit *TsB;
    QLabel *label_48;
    QLineEdit *QeA;
    QLineEdit *QeB;
    QPushButton *pushButton_ExcelA;
    QPushButton *pushButton_ExcelB;
    QPushButton *pushButton_ExcelComun;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QDialog *CRP)
    {
        if (CRP->objectName().isEmpty())
            CRP->setObjectName(QString::fromUtf8("CRP"));
        CRP->resize(1443, 945);
        centralwidget = new QWidget(CRP);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        centralwidget->setGeometry(QRect(10, 30, 1471, 921));
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(290, 30, 111, 31));
        QFont font;
        font.setPointSize(12);
        label->setFont(font);
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(410, 30, 111, 31));
        label_2->setFont(font);
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(730, 30, 111, 31));
        label_3->setFont(font);
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(850, 30, 111, 31));
        label_4->setFont(font);
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(970, 30, 111, 31));
        label_5->setFont(font);
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(1090, 30, 111, 31));
        label_6->setFont(font);
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(1210, 30, 111, 31));
        label_7->setFont(font);
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(1300, 30, 111, 31));
        label_8->setFont(font);
        CT1 = new QLineEdit(centralwidget);
        CT1->setObjectName(QString::fromUtf8("CT1"));
        CT1->setGeometry(QRect(850, 80, 81, 31));
        CT1->setFont(font);
        CT2 = new QLineEdit(centralwidget);
        CT2->setObjectName(QString::fromUtf8("CT2"));
        CT2->setGeometry(QRect(850, 120, 81, 31));
        CT2->setFont(font);
        CT3 = new QLineEdit(centralwidget);
        CT3->setObjectName(QString::fromUtf8("CT3"));
        CT3->setGeometry(QRect(850, 160, 81, 31));
        CT3->setFont(font);
        CT4 = new QLineEdit(centralwidget);
        CT4->setObjectName(QString::fromUtf8("CT4"));
        CT4->setGeometry(QRect(850, 200, 81, 31));
        CT4->setFont(font);
        CT5 = new QLineEdit(centralwidget);
        CT5->setObjectName(QString::fromUtf8("CT5"));
        CT5->setGeometry(QRect(850, 240, 81, 31));
        CT5->setFont(font);
        CT6 = new QLineEdit(centralwidget);
        CT6->setObjectName(QString::fromUtf8("CT6"));
        CT6->setGeometry(QRect(850, 280, 81, 31));
        CT6->setFont(font);
        te2 = new QLineEdit(centralwidget);
        te2->setObjectName(QString::fromUtf8("te2"));
        te2->setGeometry(QRect(960, 120, 81, 31));
        te2->setFont(font);
        te6 = new QLineEdit(centralwidget);
        te6->setObjectName(QString::fromUtf8("te6"));
        te6->setGeometry(QRect(960, 280, 81, 31));
        te6->setFont(font);
        te1 = new QLineEdit(centralwidget);
        te1->setObjectName(QString::fromUtf8("te1"));
        te1->setGeometry(QRect(960, 80, 81, 31));
        te1->setFont(font);
        te4 = new QLineEdit(centralwidget);
        te4->setObjectName(QString::fromUtf8("te4"));
        te4->setGeometry(QRect(960, 200, 81, 31));
        te4->setFont(font);
        te3 = new QLineEdit(centralwidget);
        te3->setObjectName(QString::fromUtf8("te3"));
        te3->setGeometry(QRect(960, 160, 81, 31));
        te3->setFont(font);
        te5 = new QLineEdit(centralwidget);
        te5->setObjectName(QString::fromUtf8("te5"));
        te5->setGeometry(QRect(960, 240, 81, 31));
        te5->setFont(font);
        tmp2 = new QLineEdit(centralwidget);
        tmp2->setObjectName(QString::fromUtf8("tmp2"));
        tmp2->setGeometry(QRect(1080, 120, 81, 31));
        tmp2->setFont(font);
        tmp6 = new QLineEdit(centralwidget);
        tmp6->setObjectName(QString::fromUtf8("tmp6"));
        tmp6->setGeometry(QRect(1080, 280, 81, 31));
        tmp6->setFont(font);
        tmp1 = new QLineEdit(centralwidget);
        tmp1->setObjectName(QString::fromUtf8("tmp1"));
        tmp1->setGeometry(QRect(1080, 80, 81, 31));
        tmp1->setFont(font);
        tmp4 = new QLineEdit(centralwidget);
        tmp4->setObjectName(QString::fromUtf8("tmp4"));
        tmp4->setGeometry(QRect(1080, 200, 81, 31));
        tmp4->setFont(font);
        tmp3 = new QLineEdit(centralwidget);
        tmp3->setObjectName(QString::fromUtf8("tmp3"));
        tmp3->setGeometry(QRect(1080, 160, 81, 31));
        tmp3->setFont(font);
        tmp5 = new QLineEdit(centralwidget);
        tmp5->setObjectName(QString::fromUtf8("tmp5"));
        tmp5->setGeometry(QRect(1080, 240, 81, 31));
        tmp5->setFont(font);
        a5 = new QLineEdit(centralwidget);
        a5->setObjectName(QString::fromUtf8("a5"));
        a5->setGeometry(QRect(1190, 240, 81, 31));
        a5->setFont(font);
        a2 = new QLineEdit(centralwidget);
        a2->setObjectName(QString::fromUtf8("a2"));
        a2->setGeometry(QRect(1190, 120, 81, 31));
        a2->setFont(font);
        a6 = new QLineEdit(centralwidget);
        a6->setObjectName(QString::fromUtf8("a6"));
        a6->setGeometry(QRect(1190, 280, 81, 31));
        a6->setFont(font);
        a4 = new QLineEdit(centralwidget);
        a4->setObjectName(QString::fromUtf8("a4"));
        a4->setGeometry(QRect(1190, 200, 81, 31));
        a4->setFont(font);
        a1 = new QLineEdit(centralwidget);
        a1->setObjectName(QString::fromUtf8("a1"));
        a1->setGeometry(QRect(1190, 80, 81, 31));
        a1->setFont(font);
        a3 = new QLineEdit(centralwidget);
        a3->setObjectName(QString::fromUtf8("a3"));
        a3->setGeometry(QRect(1190, 160, 81, 31));
        a3->setFont(font);
        tc5 = new QLineEdit(centralwidget);
        tc5->setObjectName(QString::fromUtf8("tc5"));
        tc5->setGeometry(QRect(1300, 240, 111, 31));
        tc5->setFont(font);
        tc2 = new QLineEdit(centralwidget);
        tc2->setObjectName(QString::fromUtf8("tc2"));
        tc2->setGeometry(QRect(1300, 120, 111, 31));
        tc2->setFont(font);
        tc6 = new QLineEdit(centralwidget);
        tc6->setObjectName(QString::fromUtf8("tc6"));
        tc6->setGeometry(QRect(1300, 280, 111, 31));
        tc6->setFont(font);
        tc4 = new QLineEdit(centralwidget);
        tc4->setObjectName(QString::fromUtf8("tc4"));
        tc4->setGeometry(QRect(1300, 200, 111, 31));
        tc4->setFont(font);
        tc1 = new QLineEdit(centralwidget);
        tc1->setObjectName(QString::fromUtf8("tc1"));
        tc1->setGeometry(QRect(1300, 80, 111, 31));
        tc1->setFont(font);
        tc3 = new QLineEdit(centralwidget);
        tc3->setObjectName(QString::fromUtf8("tc3"));
        tc3->setGeometry(QRect(1300, 160, 111, 31));
        tc3->setFont(font);
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(130, 30, 101, 51));
        QFont font1;
        font1.setPointSize(17);
        label_9->setFont(font1);
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(750, 80, 51, 31));
        label_10->setFont(font);
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(750, 120, 51, 31));
        label_11->setFont(font);
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(750, 160, 51, 31));
        label_12->setFont(font);
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(750, 200, 51, 31));
        label_13->setFont(font);
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(750, 240, 51, 31));
        label_14->setFont(font);
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(750, 280, 51, 31));
        label_15->setFont(font);
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(410, 120, 51, 31));
        label_16->setFont(font);
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(410, 240, 51, 31));
        label_17->setFont(font);
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(300, 120, 51, 31));
        label_18->setFont(font);
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(300, 240, 51, 31));
        label_19->setFont(font);
        SALIR = new QCommandLinkButton(centralwidget);
        SALIR->setObjectName(QString::fromUtf8("SALIR"));
        SALIR->setGeometry(QRect(30, 300, 111, 41));
        QFont font2;
        font2.setPointSize(7);
        SALIR->setFont(font2);
        Ejecutar = new QPushButton(centralwidget);
        Ejecutar->setObjectName(QString::fromUtf8("Ejecutar"));
        Ejecutar->setGeometry(QRect(100, 170, 131, 51));
        Ejecutar->setFont(font);
        line = new QFrame(centralwidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(30, 340, 1371, 20));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(490, 380, 111, 31));
        QFont font3;
        font3.setPointSize(15);
        label_20->setFont(font3);
        label_21 = new QLabel(centralwidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(730, 380, 111, 31));
        label_21->setFont(font3);
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(970, 380, 111, 31));
        label_22->setFont(font3);
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(40, 380, 111, 31));
        label_23->setFont(font);
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(610, 380, 111, 31));
        label_24->setFont(font3);
        label_25 = new QLabel(centralwidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(1210, 380, 111, 31));
        label_25->setFont(font3);
        label_26 = new QLabel(centralwidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(1090, 380, 111, 31));
        label_26->setFont(font3);
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(850, 380, 111, 31));
        label_27->setFont(font3);
        label_28 = new QLabel(centralwidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(1320, 380, 111, 31));
        label_28->setFont(font3);
        label_29 = new QLabel(centralwidget);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(40, 430, 391, 31));
        label_29->setFont(font);
        label_30 = new QLabel(centralwidget);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(40, 470, 391, 31));
        label_30->setFont(font);
        PPB_1 = new QLineEdit(centralwidget);
        PPB_1->setObjectName(QString::fromUtf8("PPB_1"));
        PPB_1->setGeometry(QRect(450, 470, 111, 31));
        PPB_1->setFont(font);
        PPA_1 = new QLineEdit(centralwidget);
        PPA_1->setObjectName(QString::fromUtf8("PPA_1"));
        PPA_1->setGeometry(QRect(450, 430, 111, 31));
        PPA_1->setFont(font);
        label_31 = new QLabel(centralwidget);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(10, 580, 111, 31));
        label_31->setFont(font);
        label_32 = new QLabel(centralwidget);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(70, 520, 111, 31));
        label_32->setFont(font);
        label_33 = new QLabel(centralwidget);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(90, 560, 51, 31));
        label_33->setFont(font);
        label_34 = new QLabel(centralwidget);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(90, 610, 51, 31));
        label_34->setFont(font);
        label_35 = new QLabel(centralwidget);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(180, 520, 111, 31));
        label_35->setFont(font);
        PPB_3 = new QLineEdit(centralwidget);
        PPB_3->setObjectName(QString::fromUtf8("PPB_3"));
        PPB_3->setGeometry(QRect(690, 470, 111, 31));
        PPB_3->setFont(font);
        PPA_3 = new QLineEdit(centralwidget);
        PPA_3->setObjectName(QString::fromUtf8("PPA_3"));
        PPA_3->setGeometry(QRect(690, 430, 111, 31));
        PPA_3->setFont(font);
        PPB_4 = new QLineEdit(centralwidget);
        PPB_4->setObjectName(QString::fromUtf8("PPB_4"));
        PPB_4->setGeometry(QRect(810, 470, 111, 31));
        PPB_4->setFont(font);
        PPA_4 = new QLineEdit(centralwidget);
        PPA_4->setObjectName(QString::fromUtf8("PPA_4"));
        PPA_4->setGeometry(QRect(810, 430, 111, 31));
        PPA_4->setFont(font);
        PPB_5 = new QLineEdit(centralwidget);
        PPB_5->setObjectName(QString::fromUtf8("PPB_5"));
        PPB_5->setGeometry(QRect(930, 470, 111, 31));
        QFont font4;
        font4.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font4.setPointSize(12);
        PPB_5->setFont(font4);
        PPA_5 = new QLineEdit(centralwidget);
        PPA_5->setObjectName(QString::fromUtf8("PPA_5"));
        PPA_5->setGeometry(QRect(930, 430, 111, 31));
        PPA_5->setFont(font);
        PPB_6 = new QLineEdit(centralwidget);
        PPB_6->setObjectName(QString::fromUtf8("PPB_6"));
        PPB_6->setGeometry(QRect(1050, 470, 111, 31));
        PPB_6->setFont(font);
        PPA_6 = new QLineEdit(centralwidget);
        PPA_6->setObjectName(QString::fromUtf8("PPA_6"));
        PPA_6->setGeometry(QRect(1050, 430, 111, 31));
        PPA_6->setFont(font);
        PPB_7 = new QLineEdit(centralwidget);
        PPB_7->setObjectName(QString::fromUtf8("PPB_7"));
        PPB_7->setGeometry(QRect(1170, 470, 111, 31));
        QFont font5;
        font5.setPointSize(13);
        PPB_7->setFont(font5);
        PPA_7 = new QLineEdit(centralwidget);
        PPA_7->setObjectName(QString::fromUtf8("PPA_7"));
        PPA_7->setGeometry(QRect(1170, 430, 111, 31));
        PPA_7->setFont(font);
        PPB_8 = new QLineEdit(centralwidget);
        PPB_8->setObjectName(QString::fromUtf8("PPB_8"));
        PPB_8->setGeometry(QRect(1290, 470, 111, 31));
        PPB_8->setFont(font);
        PPA_8 = new QLineEdit(centralwidget);
        PPA_8->setObjectName(QString::fromUtf8("PPA_8"));
        PPA_8->setGeometry(QRect(1290, 430, 111, 31));
        PPA_8->setFont(font);
        PPB_2 = new QLineEdit(centralwidget);
        PPB_2->setObjectName(QString::fromUtf8("PPB_2"));
        PPB_2->setGeometry(QRect(570, 470, 111, 31));
        PPB_2->setFont(font);
        PPA_2 = new QLineEdit(centralwidget);
        PPA_2->setObjectName(QString::fromUtf8("PPA_2"));
        PPA_2->setGeometry(QRect(570, 430, 111, 31));
        PPA_2->setFont(font);
        label_36 = new QLabel(centralwidget);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(270, 520, 111, 31));
        label_36->setFont(font);
        label_37 = new QLabel(centralwidget);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(370, 520, 111, 31));
        label_37->setFont(font);
        QB1 = new QLineEdit(centralwidget);
        QB1->setObjectName(QString::fromUtf8("QB1"));
        QB1->setGeometry(QRect(250, 610, 81, 31));
        QB1->setFont(font);
        AJB1 = new QLineEdit(centralwidget);
        AJB1->setObjectName(QString::fromUtf8("AJB1"));
        AJB1->setGeometry(QRect(340, 610, 101, 31));
        AJB1->setFont(font);
        TCB1 = new QLineEdit(centralwidget);
        TCB1->setObjectName(QString::fromUtf8("TCB1"));
        TCB1->setGeometry(QRect(130, 610, 111, 31));
        TCB1->setFont(font);
        TC1A = new QLineEdit(centralwidget);
        TC1A->setObjectName(QString::fromUtf8("TC1A"));
        TC1A->setGeometry(QRect(130, 560, 111, 31));
        TC1A->setFont(font);
        QA1 = new QLineEdit(centralwidget);
        QA1->setObjectName(QString::fromUtf8("QA1"));
        QA1->setGeometry(QRect(250, 560, 81, 31));
        QA1->setFont(font);
        AJA1 = new QLineEdit(centralwidget);
        AJA1->setObjectName(QString::fromUtf8("AJA1"));
        AJA1->setGeometry(QRect(340, 560, 101, 31));
        AJA1->setFont(font);
        label_38 = new QLabel(centralwidget);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(360, 660, 111, 31));
        label_38->setFont(font);
        CT1B_2 = new QLineEdit(centralwidget);
        CT1B_2->setObjectName(QString::fromUtf8("CT1B_2"));
        CT1B_2->setGeometry(QRect(580, 610, 111, 31));
        CT1B_2->setFont(font);
        CT1B_4 = new QLineEdit(centralwidget);
        CT1B_4->setObjectName(QString::fromUtf8("CT1B_4"));
        CT1B_4->setGeometry(QRect(820, 610, 111, 31));
        CT1B_4->setFont(font);
        CT1B_5 = new QLineEdit(centralwidget);
        CT1B_5->setObjectName(QString::fromUtf8("CT1B_5"));
        CT1B_5->setGeometry(QRect(940, 610, 111, 31));
        CT1B_5->setFont(font);
        CT1B_6 = new QLineEdit(centralwidget);
        CT1B_6->setObjectName(QString::fromUtf8("CT1B_6"));
        CT1B_6->setGeometry(QRect(1060, 610, 111, 31));
        CT1B_6->setFont(font);
        CT1B_8 = new QLineEdit(centralwidget);
        CT1B_8->setObjectName(QString::fromUtf8("CT1B_8"));
        CT1B_8->setGeometry(QRect(1300, 610, 111, 31));
        CT1B_8->setFont(font);
        CT1B_3 = new QLineEdit(centralwidget);
        CT1B_3->setObjectName(QString::fromUtf8("CT1B_3"));
        CT1B_3->setGeometry(QRect(700, 610, 111, 31));
        CT1B_3->setFont(font);
        CT1A_3 = new QLineEdit(centralwidget);
        CT1A_3->setObjectName(QString::fromUtf8("CT1A_3"));
        CT1A_3->setGeometry(QRect(700, 560, 111, 31));
        CT1A_3->setFont(font);
        CT1A_4 = new QLineEdit(centralwidget);
        CT1A_4->setObjectName(QString::fromUtf8("CT1A_4"));
        CT1A_4->setGeometry(QRect(820, 560, 111, 31));
        CT1A_4->setFont(font);
        CT1B_1 = new QLineEdit(centralwidget);
        CT1B_1->setObjectName(QString::fromUtf8("CT1B_1"));
        CT1B_1->setGeometry(QRect(460, 610, 111, 31));
        CT1B_1->setFont(font);
        CT1B_7 = new QLineEdit(centralwidget);
        CT1B_7->setObjectName(QString::fromUtf8("CT1B_7"));
        CT1B_7->setGeometry(QRect(1180, 610, 111, 31));
        CT1B_7->setFont(font);
        CT1A_8 = new QLineEdit(centralwidget);
        CT1A_8->setObjectName(QString::fromUtf8("CT1A_8"));
        CT1A_8->setGeometry(QRect(1300, 560, 111, 31));
        CT1A_8->setFont(font);
        CT1A_6 = new QLineEdit(centralwidget);
        CT1A_6->setObjectName(QString::fromUtf8("CT1A_6"));
        CT1A_6->setGeometry(QRect(1060, 560, 111, 31));
        CT1A_6->setFont(font);
        CT1A_1 = new QLineEdit(centralwidget);
        CT1A_1->setObjectName(QString::fromUtf8("CT1A_1"));
        CT1A_1->setGeometry(QRect(460, 560, 111, 31));
        CT1A_1->setFont(font);
        CT1A_2 = new QLineEdit(centralwidget);
        CT1A_2->setObjectName(QString::fromUtf8("CT1A_2"));
        CT1A_2->setGeometry(QRect(580, 560, 111, 31));
        CT1A_2->setFont(font);
        CT1A_7 = new QLineEdit(centralwidget);
        CT1A_7->setObjectName(QString::fromUtf8("CT1A_7"));
        CT1A_7->setGeometry(QRect(1180, 560, 111, 31));
        CT1A_7->setFont(font);
        CT1A_5 = new QLineEdit(centralwidget);
        CT1A_5->setObjectName(QString::fromUtf8("CT1A_5"));
        CT1A_5->setGeometry(QRect(940, 560, 111, 31));
        CT1A_5->setFont(font);
        T1_8 = new QLineEdit(centralwidget);
        T1_8->setObjectName(QString::fromUtf8("T1_8"));
        T1_8->setGeometry(QRect(1300, 660, 111, 31));
        T1_8->setFont(font);
        T1_6 = new QLineEdit(centralwidget);
        T1_6->setObjectName(QString::fromUtf8("T1_6"));
        T1_6->setGeometry(QRect(1060, 660, 111, 31));
        T1_6->setFont(font);
        T1_3 = new QLineEdit(centralwidget);
        T1_3->setObjectName(QString::fromUtf8("T1_3"));
        T1_3->setGeometry(QRect(700, 660, 111, 31));
        T1_3->setFont(font4);
        T1_2 = new QLineEdit(centralwidget);
        T1_2->setObjectName(QString::fromUtf8("T1_2"));
        T1_2->setGeometry(QRect(580, 660, 111, 31));
        T1_2->setFont(font);
        T1_5 = new QLineEdit(centralwidget);
        T1_5->setObjectName(QString::fromUtf8("T1_5"));
        T1_5->setGeometry(QRect(940, 660, 111, 31));
        T1_5->setFont(font);
        T1_7 = new QLineEdit(centralwidget);
        T1_7->setObjectName(QString::fromUtf8("T1_7"));
        T1_7->setGeometry(QRect(1180, 660, 111, 31));
        T1_7->setFont(font);
        T1_1 = new QLineEdit(centralwidget);
        T1_1->setObjectName(QString::fromUtf8("T1_1"));
        T1_1->setGeometry(QRect(460, 660, 111, 31));
        T1_1->setFont(font);
        T1_4 = new QLineEdit(centralwidget);
        T1_4->setObjectName(QString::fromUtf8("T1_4"));
        T1_4->setGeometry(QRect(820, 660, 111, 31));
        T1_4->setFont(font);
        TC2A = new QLineEdit(centralwidget);
        TC2A->setObjectName(QString::fromUtf8("TC2A"));
        TC2A->setGeometry(QRect(130, 750, 111, 31));
        TC2A->setFont(font);
        T2_7 = new QLineEdit(centralwidget);
        T2_7->setObjectName(QString::fromUtf8("T2_7"));
        T2_7->setGeometry(QRect(1180, 850, 111, 31));
        T2_7->setFont(font);
        CT2B_7 = new QLineEdit(centralwidget);
        CT2B_7->setObjectName(QString::fromUtf8("CT2B_7"));
        CT2B_7->setGeometry(QRect(1180, 800, 111, 31));
        CT2B_7->setFont(font);
        label_39 = new QLabel(centralwidget);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(370, 710, 111, 31));
        label_39->setFont(font);
        AJB2 = new QLineEdit(centralwidget);
        AJB2->setObjectName(QString::fromUtf8("AJB2"));
        AJB2->setGeometry(QRect(340, 800, 101, 31));
        AJB2->setFont(font);
        QA2 = new QLineEdit(centralwidget);
        QA2->setObjectName(QString::fromUtf8("QA2"));
        QA2->setGeometry(QRect(250, 750, 81, 31));
        QA2->setFont(font);
        CT2B_8 = new QLineEdit(centralwidget);
        CT2B_8->setObjectName(QString::fromUtf8("CT2B_8"));
        CT2B_8->setGeometry(QRect(1300, 800, 111, 31));
        CT2B_8->setFont(font);
        CT2A_5 = new QLineEdit(centralwidget);
        CT2A_5->setObjectName(QString::fromUtf8("CT2A_5"));
        CT2A_5->setGeometry(QRect(940, 750, 111, 31));
        CT2A_5->setFont(font);
        label_40 = new QLabel(centralwidget);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(270, 710, 111, 31));
        label_40->setFont(font);
        T2_1 = new QLineEdit(centralwidget);
        T2_1->setObjectName(QString::fromUtf8("T2_1"));
        T2_1->setGeometry(QRect(460, 850, 111, 31));
        T2_1->setFont(font);
        T2_6 = new QLineEdit(centralwidget);
        T2_6->setObjectName(QString::fromUtf8("T2_6"));
        T2_6->setGeometry(QRect(1060, 850, 111, 31));
        T2_6->setFont(font);
        CT2A_2 = new QLineEdit(centralwidget);
        CT2A_2->setObjectName(QString::fromUtf8("CT2A_2"));
        CT2A_2->setGeometry(QRect(580, 750, 111, 31));
        CT2A_2->setFont(font);
        T2_8 = new QLineEdit(centralwidget);
        T2_8->setObjectName(QString::fromUtf8("T2_8"));
        T2_8->setGeometry(QRect(1300, 850, 111, 31));
        T2_8->setFont(font);
        AJA2 = new QLineEdit(centralwidget);
        AJA2->setObjectName(QString::fromUtf8("AJA2"));
        AJA2->setGeometry(QRect(340, 750, 101, 31));
        AJA2->setFont(font);
        TC2B = new QLineEdit(centralwidget);
        TC2B->setObjectName(QString::fromUtf8("TC2B"));
        TC2B->setGeometry(QRect(130, 800, 111, 31));
        TC2B->setFont(font);
        CT2A_4 = new QLineEdit(centralwidget);
        CT2A_4->setObjectName(QString::fromUtf8("CT2A_4"));
        CT2A_4->setGeometry(QRect(820, 750, 111, 31));
        CT2A_4->setFont(font);
        CT2A_1 = new QLineEdit(centralwidget);
        CT2A_1->setObjectName(QString::fromUtf8("CT2A_1"));
        CT2A_1->setGeometry(QRect(460, 750, 111, 31));
        CT2A_1->setFont(font);
        CT2A_8 = new QLineEdit(centralwidget);
        CT2A_8->setObjectName(QString::fromUtf8("CT2A_8"));
        CT2A_8->setGeometry(QRect(1300, 750, 111, 31));
        CT2A_8->setFont(font);
        T2_3 = new QLineEdit(centralwidget);
        T2_3->setObjectName(QString::fromUtf8("T2_3"));
        T2_3->setGeometry(QRect(700, 850, 111, 31));
        T2_3->setFont(font);
        CT2B_5 = new QLineEdit(centralwidget);
        CT2B_5->setObjectName(QString::fromUtf8("CT2B_5"));
        CT2B_5->setGeometry(QRect(940, 800, 111, 31));
        CT2B_5->setFont(font);
        CT2B_3 = new QLineEdit(centralwidget);
        CT2B_3->setObjectName(QString::fromUtf8("CT2B_3"));
        CT2B_3->setGeometry(QRect(700, 800, 111, 31));
        CT2B_3->setFont(font);
        label_41 = new QLabel(centralwidget);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(360, 850, 111, 31));
        label_41->setFont(font);
        T2_4 = new QLineEdit(centralwidget);
        T2_4->setObjectName(QString::fromUtf8("T2_4"));
        T2_4->setGeometry(QRect(820, 850, 111, 31));
        T2_4->setFont(font);
        CT2B_2 = new QLineEdit(centralwidget);
        CT2B_2->setObjectName(QString::fromUtf8("CT2B_2"));
        CT2B_2->setGeometry(QRect(580, 800, 111, 31));
        CT2B_2->setFont(font);
        T2_5 = new QLineEdit(centralwidget);
        T2_5->setObjectName(QString::fromUtf8("T2_5"));
        T2_5->setGeometry(QRect(940, 850, 111, 31));
        T2_5->setFont(font);
        CT2A_3 = new QLineEdit(centralwidget);
        CT2A_3->setObjectName(QString::fromUtf8("CT2A_3"));
        CT2A_3->setGeometry(QRect(700, 750, 111, 31));
        CT2A_3->setFont(font);
        CT2B_1 = new QLineEdit(centralwidget);
        CT2B_1->setObjectName(QString::fromUtf8("CT2B_1"));
        CT2B_1->setGeometry(QRect(460, 800, 111, 31));
        CT2B_1->setFont(font);
        CT2A_7 = new QLineEdit(centralwidget);
        CT2A_7->setObjectName(QString::fromUtf8("CT2A_7"));
        CT2A_7->setGeometry(QRect(1180, 750, 111, 31));
        CT2A_7->setFont(font);
        CT2B_6 = new QLineEdit(centralwidget);
        CT2B_6->setObjectName(QString::fromUtf8("CT2B_6"));
        CT2B_6->setGeometry(QRect(1060, 800, 111, 31));
        CT2B_6->setFont(font);
        QB2 = new QLineEdit(centralwidget);
        QB2->setObjectName(QString::fromUtf8("QB2"));
        QB2->setGeometry(QRect(250, 800, 81, 31));
        QB2->setFont(font);
        label_42 = new QLabel(centralwidget);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(180, 710, 111, 31));
        label_42->setFont(font);
        label_43 = new QLabel(centralwidget);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(80, 800, 51, 31));
        label_43->setFont(font);
        CT2A_6 = new QLineEdit(centralwidget);
        CT2A_6->setObjectName(QString::fromUtf8("CT2A_6"));
        CT2A_6->setGeometry(QRect(1060, 750, 111, 31));
        CT2A_6->setFont(font);
        label_44 = new QLabel(centralwidget);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(10, 770, 111, 31));
        label_44->setFont(font);
        CT2B_4 = new QLineEdit(centralwidget);
        CT2B_4->setObjectName(QString::fromUtf8("CT2B_4"));
        CT2B_4->setGeometry(QRect(820, 800, 111, 31));
        CT2B_4->setFont(font);
        label_45 = new QLabel(centralwidget);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(80, 750, 51, 31));
        label_45->setFont(font);
        T2_2 = new QLineEdit(centralwidget);
        T2_2->setObjectName(QString::fromUtf8("T2_2"));
        T2_2->setGeometry(QRect(580, 850, 111, 31));
        T2_2->setFont(font);
        label_46 = new QLabel(centralwidget);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(70, 710, 111, 31));
        label_46->setFont(font);
        label_47 = new QLabel(centralwidget);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(520, 30, 111, 31));
        label_47->setFont(font);
        TsA = new QLineEdit(centralwidget);
        TsA->setObjectName(QString::fromUtf8("TsA"));
        TsA->setGeometry(QRect(500, 120, 81, 31));
        TsA->setFont(font);
        TsB = new QLineEdit(centralwidget);
        TsB->setObjectName(QString::fromUtf8("TsB"));
        TsB->setGeometry(QRect(500, 240, 81, 31));
        TsB->setFont(font);
        label_48 = new QLabel(centralwidget);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(620, 30, 111, 31));
        label_48->setFont(font);
        QeA = new QLineEdit(centralwidget);
        QeA->setObjectName(QString::fromUtf8("QeA"));
        QeA->setGeometry(QRect(610, 120, 81, 31));
        QeA->setFont(font);
        QeB = new QLineEdit(centralwidget);
        QeB->setObjectName(QString::fromUtf8("QeB"));
        QeB->setGeometry(QRect(610, 240, 81, 31));
        QeB->setFont(font);
        pushButton_ExcelA = new QPushButton(centralwidget);
        pushButton_ExcelA->setObjectName(QString::fromUtf8("pushButton_ExcelA"));
        pushButton_ExcelA->setGeometry(QRect(70, 120, 181, 31));
        pushButton_ExcelB = new QPushButton(centralwidget);
        pushButton_ExcelB->setObjectName(QString::fromUtf8("pushButton_ExcelB"));
        pushButton_ExcelB->setGeometry(QRect(70, 240, 181, 31));
        pushButton_ExcelComun = new QPushButton(centralwidget);
        pushButton_ExcelComun->setObjectName(QString::fromUtf8("pushButton_ExcelComun"));
        pushButton_ExcelComun->setGeometry(QRect(140, 290, 181, 41));
        menubar = new QMenuBar(CRP);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1443, 21));
        statusbar = new QStatusBar(CRP);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        statusbar->setGeometry(QRect(0, 0, 3, 22));

        retranslateUi(CRP);

        QMetaObject::connectSlotsByName(CRP);
    } // setupUi

    void retranslateUi(QDialog *CRP)
    {
        CRP->setWindowTitle(QApplication::translate("CRP", "CRP", nullptr));
        label->setText(QApplication::translate("CRP", "Item", nullptr));
        label_2->setText(QApplication::translate("CRP", "Ruta", nullptr));
        label_3->setText(QApplication::translate("CRP", "Operaci\303\263n", nullptr));
        label_4->setText(QApplication::translate("CRP", "CTk", nullptr));
        label_5->setText(QApplication::translate("CRP", "tei", nullptr));
        label_6->setText(QApplication::translate("CRP", "tmp", nullptr));
        label_7->setText(QApplication::translate("CRP", "ai", nullptr));
        label_8->setText(QApplication::translate("CRP", "tcijk (h.e.)", nullptr));
        CT1->setText(QApplication::translate("CRP", "1", nullptr));
        CT2->setText(QApplication::translate("CRP", "2", nullptr));
        CT3->setText(QApplication::translate("CRP", "1", nullptr));
        CT4->setText(QApplication::translate("CRP", "1", nullptr));
        CT5->setText(QApplication::translate("CRP", "2", nullptr));
        CT6->setText(QApplication::translate("CRP", "1", nullptr));
        te2->setText(QApplication::translate("CRP", "5", nullptr));
        te6->setText(QApplication::translate("CRP", "27", nullptr));
        te1->setText(QApplication::translate("CRP", "20", nullptr));
        te4->setText(QApplication::translate("CRP", "15", nullptr));
        te3->setText(QApplication::translate("CRP", "7", nullptr));
        te5->setText(QApplication::translate("CRP", "30", nullptr));
        tmp2->setText(QApplication::translate("CRP", "30", nullptr));
        tmp6->setText(QApplication::translate("CRP", "7", nullptr));
        tmp1->setText(QApplication::translate("CRP", "25", nullptr));
        tmp4->setText(QApplication::translate("CRP", "1", nullptr));
        tmp3->setText(QApplication::translate("CRP", "10", nullptr));
        tmp5->setText(QApplication::translate("CRP", "2", nullptr));
        a5->setText(QApplication::translate("CRP", "0.97", nullptr));
        a2->setText(QApplication::translate("CRP", "0.99", nullptr));
        a6->setText(QApplication::translate("CRP", "0.96", nullptr));
        a4->setText(QApplication::translate("CRP", "0.93", nullptr));
        a1->setText(QApplication::translate("CRP", "0.95", nullptr));
        a3->setText(QApplication::translate("CRP", "0.98", nullptr));
        tc5->setText(QString());
        tc2->setText(QString());
        tc6->setText(QString());
        tc4->setText(QString());
        tc1->setText(QString());
        tc3->setText(QString());
        label_9->setText(QApplication::translate("CRP", "CRP", nullptr));
        label_10->setText(QApplication::translate("CRP", "O1", nullptr));
        label_11->setText(QApplication::translate("CRP", "O2", nullptr));
        label_12->setText(QApplication::translate("CRP", "O3", nullptr));
        label_13->setText(QApplication::translate("CRP", "O4", nullptr));
        label_14->setText(QApplication::translate("CRP", "O5", nullptr));
        label_15->setText(QApplication::translate("CRP", "O6", nullptr));
        label_16->setText(QApplication::translate("CRP", "1", nullptr));
        label_17->setText(QApplication::translate("CRP", "2", nullptr));
        label_18->setText(QApplication::translate("CRP", "A", nullptr));
        label_19->setText(QApplication::translate("CRP", "B", nullptr));
        SALIR->setText(QApplication::translate("CRP", "Salir", nullptr));
        Ejecutar->setText(QApplication::translate("CRP", "EJECUTAR", nullptr));
        label_20->setText(QApplication::translate("CRP", "1", nullptr));
        label_21->setText(QApplication::translate("CRP", "3", nullptr));
        label_22->setText(QApplication::translate("CRP", "5", nullptr));
        label_23->setText(QApplication::translate("CRP", "Periodos", nullptr));
        label_24->setText(QApplication::translate("CRP", "2", nullptr));
        label_25->setText(QApplication::translate("CRP", "7", nullptr));
        label_26->setText(QApplication::translate("CRP", "6", nullptr));
        label_27->setText(QApplication::translate("CRP", "4", nullptr));
        label_28->setText(QApplication::translate("CRP", "8", nullptr));
        label_29->setText(QApplication::translate("CRP", "Pedidos planificados de A", nullptr));
        label_30->setText(QApplication::translate("CRP", "Pedidos planificados de B", nullptr));
        PPB_1->setText(QApplication::translate("CRP", "0", nullptr));
        PPA_1->setText(QApplication::translate("CRP", "166", nullptr));
        label_31->setText(QApplication::translate("CRP", "CT1", nullptr));
        label_32->setText(QApplication::translate("CRP", "Item", nullptr));
        label_33->setText(QApplication::translate("CRP", "A", nullptr));
        label_34->setText(QApplication::translate("CRP", "B", nullptr));
        label_35->setText(QApplication::translate("CRP", "TCjk", nullptr));
        PPB_3->setText(QApplication::translate("CRP", "0", nullptr));
        PPA_3->setText(QApplication::translate("CRP", "166", nullptr));
        PPB_4->setText(QApplication::translate("CRP", "221", nullptr));
        PPA_4->setText(QApplication::translate("CRP", "0", nullptr));
        PPB_5->setText(QApplication::translate("CRP", "0", nullptr));
        PPA_5->setText(QApplication::translate("CRP", "166", nullptr));
        PPB_6->setText(QApplication::translate("CRP", "221", nullptr));
        PPA_6->setText(QApplication::translate("CRP", "0", nullptr));
        PPB_7->setText(QApplication::translate("CRP", "0", nullptr));
        PPA_7->setText(QApplication::translate("CRP", "166", nullptr));
        PPB_8->setText(QApplication::translate("CRP", "0", nullptr));
        PPA_8->setText(QApplication::translate("CRP", "0", nullptr));
        PPB_2->setText(QApplication::translate("CRP", "221", nullptr));
        PPA_2->setText(QApplication::translate("CRP", "0", nullptr));
        label_36->setText(QApplication::translate("CRP", "Qe", nullptr));
        label_37->setText(QApplication::translate("CRP", "Aj", nullptr));
        QB1->setText(QString());
        AJB1->setText(QString());
        TCB1->setText(QString());
        TC1A->setText(QString());
        QA1->setText(QString());
        AJA1->setText(QString());
        label_38->setText(QApplication::translate("CRP", "Total", nullptr));
        CT1B_2->setText(QString());
        CT1B_4->setText(QString());
        CT1B_5->setText(QString());
        CT1B_6->setText(QString());
        CT1B_8->setText(QString());
        CT1B_3->setText(QString());
        CT1A_3->setText(QString());
        CT1A_4->setText(QString());
        CT1B_1->setText(QString());
        CT1B_7->setText(QString());
        CT1A_8->setText(QString());
        CT1A_6->setText(QString());
        CT1A_1->setText(QString());
        CT1A_2->setText(QString());
        CT1A_7->setText(QString());
        CT1A_5->setText(QString());
        T1_8->setText(QString());
        T1_6->setText(QString());
        T1_3->setText(QString());
        T1_2->setText(QString());
        T1_5->setText(QString());
        T1_7->setText(QString());
        T1_1->setText(QString());
        T1_4->setText(QString());
        TC2A->setText(QString());
        T2_7->setText(QString());
        CT2B_7->setText(QString());
        label_39->setText(QApplication::translate("CRP", "Aj", nullptr));
        AJB2->setText(QString());
        QA2->setText(QString());
        CT2B_8->setText(QString());
        CT2A_5->setText(QString());
        label_40->setText(QApplication::translate("CRP", "Qe", nullptr));
        T2_1->setText(QString());
        T2_6->setText(QString());
        CT2A_2->setText(QString());
        T2_8->setText(QString());
        AJA2->setText(QString());
        TC2B->setText(QString());
        CT2A_4->setText(QString());
        CT2A_1->setText(QString());
        CT2A_8->setText(QString());
        T2_3->setText(QString());
        CT2B_5->setText(QString());
        CT2B_3->setText(QString());
        label_41->setText(QApplication::translate("CRP", "Total", nullptr));
        T2_4->setText(QString());
        CT2B_2->setText(QString());
        T2_5->setText(QString());
        CT2A_3->setText(QString());
        CT2B_1->setText(QString());
        CT2A_7->setText(QString());
        CT2B_6->setText(QString());
        QB2->setText(QString());
        label_42->setText(QApplication::translate("CRP", "TCjk", nullptr));
        label_43->setText(QApplication::translate("CRP", "B", nullptr));
        CT2A_6->setText(QString());
        label_44->setText(QApplication::translate("CRP", "CT2", nullptr));
        CT2B_4->setText(QString());
        label_45->setText(QApplication::translate("CRP", "A", nullptr));
        T2_2->setText(QString());
        label_46->setText(QApplication::translate("CRP", "Item", nullptr));
        label_47->setText(QApplication::translate("CRP", "Ts", nullptr));
        TsA->setText(QApplication::translate("CRP", "2", nullptr));
        TsB->setText(QApplication::translate("CRP", "4", nullptr));
        label_48->setText(QApplication::translate("CRP", "Qej", nullptr));
        QeA->setText(QApplication::translate("CRP", "1500", nullptr));
        QeB->setText(QApplication::translate("CRP", "185", nullptr));
        pushButton_ExcelA->setText(QApplication::translate("CRP", "Datos A (.csv)", nullptr));
        pushButton_ExcelB->setText(QApplication::translate("CRP", "Datos B (.csv)", nullptr));
        pushButton_ExcelComun->setText(QApplication::translate("CRP", "Datos comunes CRP (.csv)", nullptr));
    } // retranslateUi

};

namespace Ui {
    class CRP: public Ui_CRP {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CRP_H
